data:
  items:
    - hashName: "AK-47 | Slate (Field-Tested)"
      maximalItemMarkupPercentage: 20.0
      stickersModule:
        enabled: true
        minimalMarkupPercentage: 1.0
        minimalStickerPrice: 10.0
    - hashName: "AK-47 | Ice Coaled (Field-Tested)"
      maximalItemMarkupPercentage: 10.0
      stickersModule:
        enabled: true
        minimalMarkupPercentage: 20.0
        minimalStickerPrice: 50.0
    - hashName: "AK-47 | Slate (Field-Tested)"
      maximalItemMarkupPercentage: 10.0
      stickersModule:
        enabled: true
        minimalMarkupPercentage: 20.0
        minimalStickerPrice: 50.0