data:
  items:
    - hashName: "AK-47 | Slate (Field-Tested)"
      maximalPage: 1000
      stickersModule:
        enabled: true
        minimalStickersPrice: 500.0
      floatModule:
        enabled: true
        minFloat: 0.20
        maxFloat: 0.24
      patternModule:
        enabled: true
        patternList: 612,118
#    - hashName: "AK-47 | Slate (Field-Tested)"
#      maximalPage: 30
#      stickersModule:
#        enabled: true
#        minimalStickersPrice: 100.0