data:
  steam_items:
    - hashName: "AK-47 | Elite Build (Field-Tested)"
      maximalPage: 3
      stickersModule:
        enabled: true
        minimalStickersPrice: 10.0
    - hashName: "M4A1-S | Nitro (Field-Tested)"
      maximalPage: 3
      stickersModule:
        enabled: true
        minimalStickersPrice: 10.0